name: Deb Package
on:
  workflow_dispatch:
    inputs:
      SOURCE_GIT_URL:
        description: 'SOURCE_GIT_URL'
        required: true
        default: 'https://github.com/microsoft/WSL2-Linux-Kernel.git'        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - name: Fetch Source Code
        run: |
          cd $GITHUB_WORKSPACE
          git clone ${{ github.event.inputs.SOURCE_GIT_URL }} kernel
      # Runs a set of commands using the runners shell
      - name: Configure Environment
        run: |
          sudo apt install build-essential flex bison dwarves libssl-dev libelf-dev cpio qemu-utils debhelper
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV
      - name: Add Config
        run: zcat $GITHUB_WORKSPACE/config.gz > $GITHUB_WORKSPACE/kernel/.config
      - name: Make
        run: |
          cd $GITHUB_WORKSPACE/kernel
          sudo make bindeb-pkg -j$(nproc)
      - name: Release
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "$GITHUB_WORKSPACE/*.deb,$GITHUB_WORKSPACE/kernel/*.deb"
          tag: "${{ env.BUILD_TIME }}"
          bodyFile: "${{ env.BUILD_TIME }}"
          token: ${{ secrets.TOKEN }}
      - name: Unexpected Name
        if: ${{ failure() }}
        run: |
          cd $GITHUB_WORKSPACE/kernel
          sed -Ei 's/^EXTRAVERSION\s*=\s*(.*[^a-zA-Z0-9])\+$/EXTRAVERSION = \1-unofficial/' Makefile
          sudo make -f debian/rules binary-arch
      - name: Failure Release
        if: ${{ failure() }}
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "$GITHUB_WORKSPACE/*.deb,$GITHUB_WORKSPACE/kernel/*.deb"
          tag: "${{ env.BUILD_TIME }}"
          bodyFile: "${{ env.BUILD_TIME }}"
          token: ${{ secrets.TOKEN }} 
